<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="s2bvdiw10dv0194" name="Default test" tests="2" failures="1" timestamp="4 Sep 2019 15:04:43 GMT" time="161.833" errors="0">
  <testcase name="feature" time="67.405" classname="TestRunner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="cucumber.runtime.CucumberException: Arity mismatch: Step Definition &amp;apos;stepDefinitions.Test.i_open_a_title_on_ProView(String) in file:/C:/Browser/ProView-NewWebApp-Automation/bin/&amp;apos; with pattern [^I failed the test cases$] is declared with 1 parameters. However, the gherkin step has 0 arguments []. 
Step: And I failed the test cases">
      <![CDATA[cucumber.runtime.CucumberException: cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'stepDefinitions.Test.i_open_a_title_on_ProView(String) in file:/C:/Browser/ProView-NewWebApp-Automation/bin/' with pattern [^I failed the test cases$] is declared with 1 parameters. However, the gherkin step has 0 arguments []. 
Step: And I failed the test cases
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'stepDefinitions.Test.i_open_a_title_on_ProView(String) in file:/C:/Browser/ProView-NewWebApp-Automation/bin/' with pattern [^I failed the test cases$] is declared with 1 parameters. However, the gherkin step has 0 arguments []. 
Step: And I failed the test cases
	at cucumber.runtime.StepDefinitionMatch.arityMismatch(StepDefinitionMatch.java:102)
	at cucumber.runtime.StepDefinitionMatch.transformedArgs(StepDefinitionMatch.java:60)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	... 25 more
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="93.164" classname="TestRunner.TestRunner"/>
</testsuite> <!-- Default test -->
